"""Placeholder sample data for pages that depend on rip-job tracking
(workflow steps 3-14), which isn't implemented yet — only disc detection
and auto-match (steps 1-2) are real. Swap these out once a real Job model
exists; route signatures are written so that swap only touches this file.
"""

SAMPLE_JOBS = [
    {
        "id": "audio-cd-sr0",
        "device": "/dev/sr0",
        "title": "Audio CD",
        "title_muted": True,
        "matched_line": "Matched: 16 Biggest Hits — The Charlie Daniels Band",
        "status": "ripping",
        "status_label": "ripping · 67%",
        "status_class": "ripping",
        "progress": 67,
        "progress_class": "ripping",
        "filter_bucket": "active",
    },
    {
        "id": "spongebob-sr1",
        "device": "/dev/sr1",
        "title": "SPONGEBOB_SQUAREPANTS",
        "title_muted": False,
        "matched_line": "Matched: SpongeBob SquarePants (1999)",
        "status": "needs_attention",
        "status_label": "needs attention",
        "status_class": "warn",
        "progress": None,
        "progress_class": None,
        "filter_bucket": "needs_attention",
    },
    {
        "id": "black-panther-sr3",
        "device": "/dev/sr3",
        "title": "BLACK_PANTHER",
        "title_muted": False,
        "matched_line": None,
        "status": "queued",
        "status_label": "queued — awaiting match",
        "status_class": "queued",
        "progress": None,
        "progress_class": None,
        "filter_bucket": "pending",
    },
    {
        "id": "toy-story-sr4",
        "device": "/dev/sr4",
        "title": "TOY_STORY",
        "title_muted": False,
        "matched_line": "Matched: Toy Story (1995)",
        "status": "encoding",
        "status_label": "encoding · 22%",
        "status_class": "encoding",
        "progress": 22,
        "progress_class": "encoding",
        "filter_bucket": "active",
    },
]

SAMPLE_JOB_DETAIL = {
    "id": "spongebob-sr1",
    "device": "/dev/sr1",
    "media_type": "DVD",
    "title": "SPONGEBOB_SQUAREPANTS",
    "status_label": "needs attention",
    "status_class": "warn",
    "candidate_type": "series",  # "movie" or "series"
    "match_title": "SpongeBob SquarePants (1999)",
    "match_source": "TMDB #387",
    "match_score": "81% text match",
    "source_summary": "720x480 MPEG-2, 9.8 Mb/s (DVD)",
    "titles": [
        {"id": 25, "selected": True, "length": "0:22:41", "season": "1", "episodes": "1-8",
         "episode_title": "Help Wanted / Reef Blower", "skipped": False},
        {"id": 26, "selected": True, "length": "0:04:22", "season": "1", "episodes": "9",
         "episode_title": "Bubblestand", "skipped": False},
        {"id": 27, "selected": False, "length": "0:00:04", "season": "", "episodes": "",
         "episode_title": "", "skipped": True},
    ],
    "encoding_selected": "h264",
}

SAMPLE_HISTORY = [
    {
        "id": "spongebob-2026-08-08",
        "disc_label": "SPONGEBOB_SQUAREPANTS",
        "matched_title": "SpongeBob SquarePants (1999) — S01E01-E08",
        "media": "DVD",
        "icon": "ti-device-tv",
        "status": "completed",
        "date": "Aug 8, 2026",
        "info": "H.264 · 1 file · 6.5 GB",
    },
    {
        "id": "charlie-daniels-2026-08-08",
        "disc_label": None,
        "matched_title": "16 Biggest Hits — The Charlie Daniels Band",
        "media": "Audio CD",
        "icon": "ti-disc",
        "status": "completed",
        "date": "Aug 8, 2026",
        "info": "FLAC · 16 tracks · 1.1 GB",
    },
    {
        "id": "black-panther-2026-08-03",
        "disc_label": "BLACK_PANTHER",
        "matched_title": None,
        "media": "Blu-ray",
        "icon": "ti-movie",
        "status": "failed",
        "date": "Aug 3, 2026",
        "info": "Rip failed — drive read error on title 3",
    },
    {
        "id": "toy-story-2026-07-28",
        "disc_label": "TOY_STORY",
        "matched_title": "Toy Story (1995)",
        "media": "DVD",
        "icon": "ti-movie",
        "status": "completed",
        "date": "Jul 28, 2026",
        "info": "H.265 · 1 file · 2.1 GB",
    },
]

SAMPLE_HISTORY_DETAIL = {
    "id": "spongebob-2026-08-08",
    "disc_label": "SPONGEBOB_SQUAREPANTS",
    "media": "DVD",
    "status": "completed",
    "date": "Aug 8, 2026",
    "device": "/dev/sr0",
    "total_time": "41m",
    "match_title": "SpongeBob SquarePants (1999)",
    "match_type": "Series",
    "match_source": "TMDB #2225",
    "match_confidence": "96%",
    "titles": [
        {"ep": "S01E01", "name": "Help Wanted / Reef Blower.mkv", "dur": "23m", "size": "610 MB"},
        {"ep": "S01E02", "name": "Tea at the Treedome / Bubblestand.mkv", "dur": "23m", "size": "604 MB"},
        {"ep": "S01E03", "name": "Jellyfishing / Plankton!.mkv", "dur": "23m", "size": "597 MB"},
        {"ep": "S01E04", "name": "Naughty Nautical Neighbors / Boating School.mkv", "dur": "23m", "size": "601 MB"},
        {"ep": "S01E05", "name": "Pizza Delivery / Home Sweet Pineapple.mkv", "dur": "23m", "size": "609 MB"},
        {"ep": "S01E06", "name": "Mermaidman and Barnacleboy I / Squeaky Boots.mkv", "dur": "23m", "size": "598 MB"},
        {"ep": "S01E07", "name": "Sandy's Rocket / F.U.N.mkv", "dur": "23m", "size": "592 MB"},
        {"ep": "S01E08", "name": "Squeaky Boots / Nature Pants.mkv", "dur": "23m", "size": "603 MB"},
    ],
    "profile": "custom",
    "params": {
        "Video codec": "H.265 (HEVC)", "Container": "MKV", "Resolution": "720×480 (source)",
        "Rate control": "CRF 20", "Encoder preset": "Slow", "Audio codec": "AAC",
        "Audio bitrate": "192 kbps, stereo", "Subtitles": "Soft (SRT), English", "Deinterlacing": "On (bwdif)",
    },
    "transfer_path": "/GH_Server/Media/TV/SpongeBob SquarePants (1999)",
    "timeline": [
        ("Disc inserted", "2:14 PM"), ("Rip started", "2:16 PM"), ("Rip finished", "2:44 PM"),
        ("Encoding finished", "2:53 PM"), ("Transfer complete", "2:55 PM"),
    ],
}
